### ISSUE TITLE
Where are the native calls made?

### ISSUE THREAD

**Issue by dheerajbhaskar** [pqy330/apktool#15]
Hi, There are native libs (.so) files and I don't know where they are loaded or used. I can't find any native functions. 

Please let me know. A one line answer/reply will also do. Thanks in advance.

PS: I'm looking at the 5.1 version of apk

**Comment by dongfangxunlei** [comment]
native libs are not used directly in java code.
the java code just call native program like java and 7za,etc

**Comment by dheerajbhaskar** [comment]
Thanks for the timely response, dongfang.

The zipped file was given an extension .so and was in libs, that confused
me. Now I understand.

I'm yet to understand the code fully. I've read that decoding in /data or
/cache is atleast 5 times faster than doing it in /sdcard.

You've commented out cache code, so where does it currently decode? will it
reduce performance?

Regards,
Dheeraj

**Comment by dongfangxunlei** [comment]
Depends on where you put the apk file you want to decode.
Decoding  in /cache or /data needs root permission.But some phone running androidl cannot execute aapt when using root.So performance is not the only thing you need to consider.

**Comment by dheerajbhaskar** [comment]
We can copy the apk to /data/data/<packagename> folder which requires no
root and decompile there. We might of course have to do a cleanup and move
files to SD card where a user can look at it, but do you see issues with
this? Is this implemented or can it be implemented?

I'm planning to use this as part of our app and might contribute back if it
works out for us.


Please let me know your thoughts.

**Comment by dongfangxunlei** [comment]
copy apk and the decompiled source need more time,I think.But you can have a test.

**Comment by dheerajbhaskar** [comment]
Oh okay. Thanks for taking the time to answer my questions. I'm planning to use this codebase. I shall contribute back my changes if I use this.
